export type Permission =
  | 'dashboard.read'
  | 'reports.read'
  | 'evaluations.read'
  | 'evaluations.create'
  | 'evaluations.edit'
  | 'evaluations.delete'
  | 'evaluations.export'
  | 'specialists.read'
  | 'specialists.edit'
  | 'teams.read'
  | 'users.read'
  | 'users.create'
  | 'users.edit'
  | 'users.delete'
  | 'settings.read'
  | 'settings.edit'
  | 'notifications.read'
  | 'notifications.manage'

